apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-04-dev-03
  namespace: pacman-04-argocd
spec:
  project: pacman-04
  destination:
    namespace: pacman-04-dev-03
    server: https://kubernetes.default.svc
  source:
    path: pacman-04/dev-03-05
    targetRevision: main
    repoURL: https://github.com/marrober/argocd-app-deployment.git
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions: 
      - Validate=true 
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground 
      - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s 